# docker compose file for the app Laravel
services:
  app-mysql:
    image: mysql
    container_name: app-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      - app-net
    volumes:
      - app-laravel-mysql-volume:/var/lib/mysql

  app-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-laravel
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - app-mysql
    volumes:
      - ./src:/var/www/html

networks:
  app-net:
    driver: bridge

volumes:
  app-laravel-mysql-volume:
    driver: local